@IF_NOT_DEF(@STD_IO_ASM_INCLUDE_GUARD,
    @MACRO(@STD_IO_ASM_INCLUDE_GUARD, (), ())

    @MACRO(@GPU_STATE_READY, (), 0x0001)
    @MACRO(@GPU_STATE_BUSY, (), 0x0002)
    @MACRO(@GPU_STATE_DATA_UPLOAD_DONE, (), 0x0003)
    @MACRO(@GPU_STATE_DATA_UPLOAD_REQUEST, (), 0x0004)

    @MACRO(@GPU_STATE_MODE_0, (), 0x0005) # Single line upload
    @MACRO(@GPU_STATE_MODE_1, (), 0x0006)
    @MACRO(@GPU_STATE_SWAP_BUFFERS, (), 0x0007)

    @MACRO(@GPU_STATE_REGISTER, (), 0x0000)
    @MACRO(@GPU_DATA_REGISTER, (), 0x0001)
    @MACRO(@GPU_SCREEN_REGISTER, (), 0x0007)

    @MACRO(@CONTEXT, (@DEVICE, @BODY),
        device @DEVICE

        @BODY
    )
)

